stages:
  preprocess_data:
    cmd: python src/preprocess.py data/raw_data.csv res/processed_data.csv
    deps:
      - data/raw_data.csv
    outs:
      - res/processed_data.csv

  train:
    cmd: python src/train.py --learning_rate ${lr} --num_epochs ${train.epochs} --test_size ${train.test_size}
    deps:
      - res/processed_data.csv
      - src/train.py
    outs:
      - models/iris_model.pkl
    metrics:
      - metrics/iris_metrics.json:
          cache: false
    plots:
      - plot/epoch_metrics.csv:
          cache: false
      - plot/learning_curves.png:
          cache: false
    params:
      - lr
      - train.epochs
      - train.test_size
